ejercicio6 y test
Algoritmos-2/A2-obligatorio-2024-S1-letra pull request #5
Opened 2024-03-27 20:37 UTC by horaciomathias

2024-03-30 11:57 UTC, BRJoaquin requested changes

2024-03-30 11:57 UTC, BRJoaquin commented on docs/ejercicios/ejercicio6.md
> +`barrio1` `barrio2` `distancia` `flujo` `estado`
@horaciomathias cual es el criterio de ordenacion para que nos de el mismo output?

2024-03-30 11:57 UTC, BRJoaquin commented on docs/ejercicios/ejercicio6.md
> +`Estado promedio de las calles reparadas: Y`
El promedio es un entero? se redondea hacia abajo?

2024-03-30 11:57 UTC, BRJoaquin commented on docs/ejercicios/ejercicio6.md
> +- Resolver en `O(L * log B)`
usar Latex 
$[tu latex]$

2024-03-30 11:57 UTC, BRJoaquin commented on docs/ejercicios/ejercicio6.md
> +### Input
@horaciomathias podes agregar un ejemplo donde tenga que desempatar con flujo y/o estado? Asi se agrega explicacion.

2024-03-30 11:57 UTC, BRJoaquin commented on docs/ejercicios/ejercicio6.md
> +   - `barrio1` y `barrio2` serán enteros que simbolizan los barrios
Aclarar que en base 1 ( de 1 a B)

2024-03-31 21:12 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +`barrio1` `barrio2` `distancia` `flujo` `estado`
Lo hice más explicito en la letra y además agregué un id para cada calle. Así, cada arista pueda ser ordenada considerando este atributo y definitivamente establecer un orden si los 3 anteriores no lo determinaron. Se clasifican siguiendo el criterio:
- menor distancia
- mejor estado (1 es el mejor estado)
- mayor flujo vehicular
- menor id de calle

2024-03-31 21:12 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +`Estado promedio de las calles reparadas: Y`
Se estaba redondeando hacia abajo, aproveché a usar round de cmath. Dejo comentario en la letra al respecto.

2024-03-31 21:22 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +- Resolver en `O(L * log B)`
Ok, done.

2024-03-31 21:28 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +### Input
Cambié el ejemplo de la letra para que lo puedan correr a mano. Este ejemplo tiene todos los escenarios de clasificación.

2024-03-31 21:29 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +   - `barrio1` y `barrio2` serán enteros que simbolizan los barrios
Agregué una restricción para cada barrio

2024-04-04 01:14 UTC, fedevilensky requested changes
hice dos sugerencias medio boludas, mas alla de eso me gusto mucho y creo que estaria ya pronto

2024-04-04 01:14 UTC, fedevilensky commented on docs/ejercicios/ejercicio6.md
> +   - por último, el id de la calle
```suggestion
   1. la menor distancia 
   1. luego el mejor estado 
   1. el mayor flujo vehicular
   1. por último, el id de la calle
```

2024-04-04 01:14 UTC, fedevilensky commented on docs/ejercicios/ejercicio6.md
> +- si lo anterior no establece un orden, se considerará la calle con id más pequeño primero
Habria que aclarar, como si se hace mas abajo, que lo primero que hay que tomar en cuenta es la distancia

```suggestion
1. se seleccionará el camino de menor distancia
1. si dos o más caminos tienen la misma distancia se preferirá reparar aquel que tenga mejor estado;
1. si el criterio anterior no es suficiente, se priorizará aquella calle que admita un mayor flujo de tránsito vehicular; y,
1. si lo anterior no establece un orden, se considerará la calle con id más pequeño primero
```

2024-04-04 01:14 UTC, fedevilensky commented on docs/ejercicios/ejercicio6.md
> +- si lo anterior no establece un orden, se considerará la calle con id más pequeño primero
y numerado porque es por orden

2024-04-05 16:40 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +   - por último, el id de la calle
Ok. Agregué numeración al criterio

2024-04-05 16:41 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +- si lo anterior no establece un orden, se considerará la calle con id más pequeño primero
ok. Agregué el criterio de la distancia y numeración que se corresponde caso a caso con la del comentario anterior

2024-04-05 16:43 UTC, horaciomathias commented on docs/ejercicios/ejercicio6.md
> +### Input
Hay un nuevo ejemplo, más corto, con 4 barrios y 5 calles, para que lo puedan correr a mano.

2024-04-05 21:11 UTC, fedevilensky approved these changes

2024-04-06 19:59 UTC, BRJoaquin approved these changes

2024-04-06 19:59 UTC, merged